#!/usr/bin/env bash

set -uo pipefail

bide_bin="${BIDE_BIN:-$HOME/.local/bin/bide}"

if [[ ! -x "$bide_bin" ]]; then
    printf '%s\0nonselectable\x1ftrue\n' "Bide is not installed"
    exit 0
fi

exec "$bide_bin" rofi "$@"
