#!/usr/bin/env bash
set -euo pipefail

pactl set-default-sink alsa_output.pci-0000_00_1f.3.pro-output-0

while read -r INPUT_ID _; do
  pactl move-sink-input "$INPUT_ID" alsa_output.pci-0000_00_1f.3.pro-output-0
done < <(pactl list short sink-inputs)
